HSA-84: troubleshooting deployment

diff --git a/deployment/testing/integration/Dockerfile b/deployment/testing/integration/Dockerfile
--- a/deployment/testing/integration/Dockerfile
+++ b/deployment/testing/integration/Dockerfile
@@ -54,8 +54,8 @@ ENV INTEGRATION_FLAG=1
 RUN chmod +x ../deployment/testing/integration/install-chromedriver.sh \
     && chmod +x ../deployment/testing/integration/install-chrome.sh
 
-RUN ../deployment/testing/integration/install-chromedriver.sh
-RUN ../deployment/testing/integration/install-chrome.sh
+RUN ../deployment/testing/integration/install-chrome.sh || { echo "Chrome installation failed"; exit 1; }
+RUN ../deployment/testing/integration/install-chromedriver.sh || { echo "ChromeDriver installation failed"; exit 1; }
 
 # Setup backend
 RUN pip3 install --no-cache-dir -r requirements.txt
